---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity<-read.csv("~/Data Scientist Course/Reproducible Research/activity.csv", header=TRUE)

activity$day <- weekdays(as.Date(activity$date))                 #extract week days
activity$DateTime<- as.POSIXct(activity$date, format="%Y-%m-%d") #change date format


## What is mean total number of steps taken per day?

#sum data by date
steps_by_day <- aggregate(steps ~ date, activity, sum)

#create histogram
hist(steps_by_day$steps, breaks=5,main="Total Steps by Day", xlab="steps")

#calculate mean and median

as.integer(mean(steps_by_day$steps))
as.integer(median(steps_by_day$steps))


## What is the average daily activity pattern?

steps_by_interval <- aggregate(steps ~ interval, activity, mean)

#create time series
plot(steps_by_interval$interval,steps_by_interval$steps, 
     type="l", xlab="Interval", ylab="Number of Steps",
     main="Average Number of Steps per Day by Interval")

## Imputing missing values

#total rows NA
incomplete <- sum(!complete.cases(activity))

#imputing data
imputed_data <- transform(activity, 
                          steps = ifelse(is.na(activity$steps), 
                          steps_by_interval$steps[match(activity$interval, 
                          steps_by_interval$interval)], activity$steps))

imputed_data[as.character(imputed_data$date) == "2012-10-01", 1] <- 0

#create histogram
steps_by_day_i <- aggregate(steps ~ date, imputed_data, sum)
hist(steps_by_day_i$steps, main = paste("Total Steps Each Day"), col="blue", xlab="Number of Steps")

hist(steps_by_day$steps, main = paste("Total Steps Each Day"), col="red", xlab="Number of Steps", add=T)
legend("topright", c("Imputed", "Non-imputed"), col=c("blue", "red"), lwd=10)

#what is the diff between imputted and non imputted data
diff <- sum(steps_by_day_i$steps) - sum(steps_by_day$steps)
as.integer(diff)


## Are there differences in activity patterns between weekdays and weekends?

weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", 
              "Friday")
imputed_data$dow = as.factor(ifelse(is.element(weekdays(as.Date(imputed_data$date)),weekdays), "Weekday", "Weekend"))

steps_by_interval_i <- aggregate(steps ~ interval + dow, imputed_data, mean)

library(lattice)

xyplot(steps_by_interval_i$steps ~ steps_by_interval_i$interval|steps_by_interval_i$dow, main="Average Steps per Day by Interval",xlab="Interval", ylab="Steps",layout=c(1,2), type="l")


